[".vim/pack/lut1a/start/surround"]
    type = "archive"
    url = "https://github.com/tpope/vim-surround/archive/refs/heads/master.zip"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".vim/pack/lut1a/start/commentary"]
    type = "archive"
    url = "https://github.com/tpope/vim-commentary/archive/refs/heads/master.zip"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".vim/pack/lut1a/start/tablemode"]
    type = "archive"
    url = "https://github.com/dhruvasagar/vim-table-mode/archive/refs/heads/master.zip"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".zsh/syntaxhigh"]
    type = "archive"
    url = "https://github.com/zsh-users/zsh-syntax-highlighting/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
    include = ["*/zsh-syntax-highlighting.zsh", "*/.version", "*/.revision-hash", "*/highlighters/**"]
[".zsh/morecompletions"]
    type = "archive"
    url = "https://github.com/zsh-users/zsh-completions/archive/refs/heads/master.zip"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
    include = ["*/src/**"]
[".zsh/historysubstringsearch.zsh"]
    type = "file"
    url = "https://raw.githubusercontent.com/zsh-users/zsh-history-substring-search/master/zsh-history-substring-search.zsh"
    refreshPeriod = "168h"
[".zsh/autosugg"]
    type = "archive"
    url = "https://github.com/zsh-users/zsh-autosuggestions/archive/refs/heads/master.zip"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"

